version: '3.1'
services:
  web_test:
    build:
      context: .
    command: bash -c 'npm run test'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app:delegated
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
    environment:
      - NODE_ENV=test
      - SERVICE_NAME=${SERVICE_NAME}
