version: '3.1'
services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: bash -c 'npm run dev'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app:delegated
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=${SERVICE_NAME}
