version: '3.1'
services:
  web_test:
    build:
      context: .
    command: bash -c 'npm run test'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/node/app:delegated
      - ./package.json:/usr/node/package.json
      - ./package-lock.json:/usr/node/package-lock.json
      - notused:/usr/node/app/node_modules
    environment:
      - NODE_ENV=test
      - SERVICE_NAME=${SERVICE_NAME}
volumes:
  notused:
